spring:
  application:
    name: backend


  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}


  sql:
    init:
      mode: always

  cloud:
    aws:
      secretsmanager:
        region: eu-north-1

jwt:
  private.key: classpath:./jwt-keys/app.key
  public.key: classpath:./jwt-keys/app.pub


logging:
  level:
    org.springframework:
      security: trace


management:
  endpoints:
    web:
      exposure:
        include: health, info



